services:
  gerry-ai:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8000:8000'
      - '4455:4455'
    volumes:
      - ../:/app
      - ../config:/app/config
      - ../data/audiobackup:/app/data/audiobackup
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_NAME=GerryAI
    env_file:
      - ../config/keys.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 30s
      timeout: 10s
      retries: 3
    command: python main.py --bot ${BOT_NAME:-GerryAI}
